import { Arimo, Inter, Manrope, Open_Sans, Roboto_Flex } from "next/font/google";
import "./globals.css";
const inter = Arimo({ subsets: ["latin"] });

export const metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {children}
        
      </body>
    </html>
  );
}
